version: "3"
services:
  gatsby:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: gatsby develop -H 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - /app/node_modules
      - .:/app
